/**
 * Optional real pixel decoder (issue #17, PIPE-010, m5).
 *
 * Decodes Code 128 barcodes directly from rendered RGBA frame pixels for
 * candidate label regions (projected quads from the geometry engine).
 * Emits results under the same observation/result contracts as the
 * analytic geometry model, stamped `processingMode: 'PIXEL_DECODER'`.
 *
 * Scope: this is a SYNTHETIC PIXEL EXPERIMENT — it decodes the app's own
 * rendered preview texture (generated by bwip-js). It is NOT a claim that
 * real camera/optics/noise handling works; see README "Pixel decoder
 * experiment" and the limitations section.
 *
 * The symbol table and checksum formula are bwip-js's (see code128Table.ts
 * header) — bwip emits a legacy Code 128 with a position-weighted checksum
 * that deviates from ISO 15417, and the decoder mirrors it so this app's
 * labels decode.
 *
 * No DOM/WebGL dependencies: takes a plain RGBA buffer, so unit tests run
 * headless against bwip-generated renders.
 */

import {
  CODE128_FNC1,
  CODE128_FNC2,
  CODE128_FNC3,
  CODE128_LATCH_A_B,
  CODE128_LATCH_A_C,
  CODE128_LATCH_B_A,
  CODE128_LATCH_B_C,
  CODE128_LATCH_C_A,
  CODE128_LATCH_C_B,
  CODE128_PATTERNS,
  CODE128_SHIFT,
  CODE128_START_A,
  CODE128_START_B,
  CODE128_START_C,
  CODE128_STOP,
} from './code128Table';

export interface PixelFrame {
  /** RGBA, row-major, widthPx*heightPx*4. */
  data: Uint8Array;
  widthPx: number;
  heightPx: number;
}

export interface PixelLabelCandidate {
  labelInstanceId: string;
  /**
   * 4 projected label corners in image pixels, in `projectedCornersPx`
   * order: (−u,−v), (+u,−v), (+u,+v), (−u,+v).
   */
  quadPx: [number, number][];
}

/**
 * Same decode-contract shape as the pipeline's `DecodeResult`, plus the
 * mode stamp (PIPE-010: mode reported in every run).
 */
export interface PixelDecodeResult {
  labelInstanceId: string;
  decoded: boolean;
  decodedPayload?: string;
  /** 0..1 — fraction of scan lines that agree on the winning payload. */
  confidence: number;
  /** Pixel-domain reason codes, e.g. 'PIXEL:CHECKSUM_FAIL'. */
  reasons: string[];
  processingMode: 'PIXEL_DECODER';
  scanLines: number;
  scanLinesDecoded: number;
}

type Mode = 'A' | 'B' | 'C';

const SCAN_VS = [0.22, 0.28, 0.34, 0.4, 0.46, 0.52, 0.58, 0.64, 0.68];
// >= 1 sample per pixel for labels up to ~800px wide (24-digit C payloads),
// so 1-module (>=4px at scene scale) bars keep >= 4 samples for stable
// quantization.
const SAMPLES = 1024;
/** Winning payload needs at least this fraction of decoded scan lines. */
const CONSENSUS = 0.5;

type LineFailure = 'NO_START' | 'BAD_SYMBOL' | 'CHECKSUM_FAIL' | 'NO_STOP' | 'DEGENERATE';

interface LineDecode {
  payload?: string;
  failure?: LineFailure;
}

/** Bilinear map from unit quad (u,v) in [0,1]² to image pixel coords. */
function quadPoint(quad: [number, number][], u: number, v: number): [number, number] {
  const [c0, c1, c2, c3] = quad;
  const x =
    c0[0] + (c1[0] - c0[0]) * u + (c3[0] - c0[0]) * v + (c2[0] - c1[0] - c3[0] + c0[0]) * u * v;
  const y =
    c0[1] + (c1[1] - c0[1]) * u + (c3[1] - c0[1]) * v + (c2[1] - c1[1] - c3[1] + c0[1]) * u * v;
  return [x, y];
}

function luminanceAt(frame: PixelFrame, x: number, y: number): number {
  const { data, widthPx, heightPx } = frame;
  if (x < 0 || y < 0 || x >= widthPx - 1 || y >= heightPx - 1) return 255;
  const x0 = Math.floor(x);
  const y0 = Math.floor(y);
  const fx = x - x0;
  const fy = y - y0;
  let sum = 0;
  for (let dy = 0; dy < 2; dy++) {
    for (let dx = 0; dx < 2; dx++) {
      const i = ((y0 + dy) * widthPx + x0 + dx) * 4;
      const lum = 0.2126 * data[i] + 0.7152 * data[i + 1] + 0.0722 * data[i + 2];
      const w = (dx === 0 ? 1 - fx : fx) * (dy === 0 ? 1 - fy : fy);
      sum += lum * w;
    }
  }
  return sum;
}

function sampleLine(frame: PixelFrame, quad: [number, number][], v: number): Float64Array {
  const line = new Float64Array(SAMPLES);
  // Full quad span: the stop guard sits flush with the quad edge for
  // tightly-fitted quads, so any inset would clip the stop on wide labels.
  for (let i = 0; i < SAMPLES; i++) {
    const u = i / (SAMPLES - 1);
    const [x, y] = quadPoint(quad, u, v);
    line[i] = luminanceAt(frame, x, y);
  }
  return line;
}

/** Otsu threshold over a luminance line. */
function otsu(line: Float64Array): number {
  const bins = 256;
  const hist = new Array<number>(bins).fill(0);
  for (const l of line) hist[Math.min(bins - 1, Math.max(0, Math.round(l)))]++;
  const total = line.length;
  let sumAll = 0;
  for (let i = 0; i < bins; i++) sumAll += i * hist[i];
  let sumB = 0;
  let wB = 0;
  let best = 127;
  let maxVariance = -1;
  for (let t = 0; t < bins; t++) {
    wB += hist[t];
    if (wB === 0) continue;
    const wF = total - wB;
    if (wF === 0) break;
    sumB += t * hist[t];
    const mB = sumB / wB;
    const mF = (sumAll - sumB) / wF;
    const variance = wB * wF * (mB - mF) * (mB - mF);
    if (variance > maxVariance) {
      maxVariance = variance;
      best = t;
    }
  }
  return best;
}

interface Runs {
  lens: number[];
  isDark: boolean[];
}

function toRuns(line: Float64Array, threshold: number): Runs {
  const lens: number[] = [];
  const isDark: boolean[] = [];
  let cur = line[0] <= threshold;
  let len = 0;
  for (const l of line) {
    const dark = l <= threshold;
    if (dark === cur) len++;
    else {
      lens.push(len);
      isDark.push(cur);
      cur = dark;
      len = 1;
    }
  }
  lens.push(len);
  isDark.push(cur);
  return { lens, isDark };
}

/**
 * Estimate the module width (in samples): the barcode's narrowest elements
 * are 1-module bars/spaces; take the median of the shortest quartile.
 */
function estimateModule(lens: number[]): number {
  const sorted = [...lens].sort((a, b) => a - b);
  const q = Math.max(1, Math.floor(sorted.length / 4));
  return [...sorted.slice(0, q)].sort((a, b) => a - b)[Math.floor(q / 2)];
}

function quantize(len: number, module: number): number {
  const q = Math.round(len / module);
  return Math.min(4, Math.max(1, q));
}

function matchSymbol(runs: Runs, cursor: number, direction: 1 | -1): number | undefined {
  for (let k = 0; k < 6; k++) {
    const i = direction === 1 ? cursor + k : cursor - k;
    if (i < 0 || i >= runs.lens.length) return undefined;
    if (runs.isDark[i] !== (k % 2 === 0)) return undefined;
  }
  const module = estimateModule(runs.lens);
  const q: number[] = [];
  for (let k = 0; k < 6; k++) {
    const i = direction === 1 ? cursor + k : cursor - k;
    q.push(quantize(runs.lens[i], module));
  }
  if (q.reduce((a, b) => a + b, 0) !== 11) return undefined;
  const key = q.join(',');
  for (let v = 0; v < CODE128_PATTERNS.length; v++) {
    if (CODE128_PATTERNS[v].join(',') === key) return v;
  }
  return undefined;
}

function decodeRuns(runs: Runs, direction: 1 | -1): LineDecode {
  // Locate the first dark run in the scan direction.
  let idx = direction === 1 ? 0 : runs.isDark.length - 1;
  while (idx >= 0 && idx < runs.isDark.length && !runs.isDark[idx]) {
    idx += direction;
  }
  if (idx < 0 || idx >= runs.isDark.length) return { failure: 'NO_START' };

  const step = direction;
  // 1) Find a start symbol.
  let pos = idx;
  let mode: Mode | undefined;
  let startVal = 0;
  while (pos + 5 < runs.lens.length) {
    if (runs.isDark[pos]) {
      const v = matchSymbol(runs, pos, step);
      if (v === CODE128_START_A || v === CODE128_START_B || v === CODE128_START_C) {
        startVal = v;
        mode = v === CODE128_START_B ? 'B' : v === CODE128_START_C ? 'C' : 'A';
        break;
      }
    }
    pos += 1;
  }
  if (mode === undefined) return { failure: 'NO_START' };

  // 2) Walk symbols after the start until the stop; the symbol immediately
  //    before the stop is the checksum symbol.
  const rest: number[] = [];
  let cursor = pos + 6 * step;
  let sawStop = false;
  while (true) {
    // skip stray light runs (should not happen; tolerate sampling noise)
    if (cursor < 0 || cursor >= runs.lens.length) return { failure: 'NO_STOP' };
    if (runs.isDark[cursor]) break;
    cursor += step;
  }
  for (;;) {
    const v = matchSymbol(runs, cursor, step);
    if (v === undefined) return { failure: 'BAD_SYMBOL' };
    if (v === CODE128_STOP) {
      sawStop = true;
      break;
    }
    rest.push(v);
    cursor += 6 * step;
  }
  if (!sawStop || rest.length === 0) return { failure: 'NO_STOP' };

  // 3) Checksum: (start + sum_i data[i]*i) mod 103, i = 1..n.
  const check = rest[rest.length - 1];
  const data = rest.slice(0, -1);
  let csum = startVal;
  for (let i = 0; i < data.length; i++) csum += data[i] * (i + 1);
  if (csum % 103 !== check) return { failure: 'CHECKSUM_FAIL' };

  // 4) Payload.
  let payload = '';
  let m: Mode = mode;
  for (const v of data) {
    const r = decodeSymbol(v, m);
    if (r.error) return { failure: 'BAD_SYMBOL' };
    payload += r.text;
    if (r.mode) m = r.mode;
  }
  return { payload };
}

interface SymbolOut {
  text: string;
  mode?: Mode;
  error?: true;
}

function decodeSymbol(v: number, mode: Mode): SymbolOut {
  // C mode: values 0..99 are digit pairs (99 is also a latch value — the
  // mode decides). 100/101 are C->B / C->A latches, 102 is FNC1: fall
  // through to the latch/FNC handling below.
  if (mode === 'C' && v <= 99) return { text: String(v).padStart(2, '0') };
  switch (v) {
    case CODE128_LATCH_B_C:
    case CODE128_LATCH_A_C:
      return { text: '', mode: 'C' };
    case CODE128_LATCH_C_B:
    case CODE128_LATCH_A_B:
      return { text: '', mode: 'B' };
    case CODE128_LATCH_B_A:
    case CODE128_LATCH_C_A:
      return { text: '', mode: 'A' };
    case CODE128_FNC1:
    case CODE128_FNC2:
    case CODE128_FNC3:
    case CODE128_SHIFT:
      return { text: '', error: true };
    default:
      break;
  }
  if (v > 99) return { text: '', error: true };
  switch (mode) {
    case 'B':
      if (v > 94) return { text: '', error: true };
      return { text: String.fromCharCode(32 + v) };
    case 'A':
      if (v > 94) return { text: '', error: true };
      return { text: String.fromCharCode(v) };
  }
  return { text: '', error: true };
}

function decodeLine(frame: PixelFrame, quad: [number, number][], v: number): LineDecode {
  const line = sampleLine(frame, quad, v);
  const threshold = otsu(line);
  const runs = toRuns(line, threshold);
  if (estimateModule(runs.lens) < 0.75) return { failure: 'DEGENERATE' };
  const fwd = decodeRuns(runs, 1);
  if (fwd.payload !== undefined) return fwd;
  const bwd = decodeRuns(runs, -1);
  if (bwd.payload !== undefined) return bwd;
  return fwd.failure === 'NO_START' || fwd.failure === 'DEGENERATE' ? bwd : fwd;
}

export function pixelDecodeFrame(
  frame: PixelFrame,
  candidates: PixelLabelCandidate[],
): PixelDecodeResult[] {
  const out: PixelDecodeResult[] = [];
  for (const cand of candidates) {
    const base: Pick<PixelDecodeResult, 'labelInstanceId' | 'processingMode' | 'scanLines'> = {
      labelInstanceId: cand.labelInstanceId,
      processingMode: 'PIXEL_DECODER',
      scanLines: SCAN_VS.length,
    };
    // 1) Sanity: corners inside the frame and label wide enough.
    const pts = cand.quadPx;
    if (
      pts.length !== 4 ||
      pts.some(
        ([x, y]) =>
          !Number.isFinite(x) ||
          !Number.isFinite(y) ||
          x < -0.5 ||
          y < -0.5 ||
          x > frame.widthPx + 0.5 ||
          y > frame.heightPx + 0.5,
      )
    ) {
      out.push({
        ...base,
        decoded: false,
        confidence: 0,
        reasons: ['PIXEL:OUT_OF_FRAME'],
        scanLinesDecoded: 0,
      });
      continue;
    }
    const widthPx = Math.hypot(pts[1][0] - pts[0][0], pts[1][1] - pts[0][1]);
    if (widthPx < 24) {
      out.push({
        ...base,
        decoded: false,
        confidence: 0,
        reasons: ['PIXEL:DEGENERATE'],
        scanLinesDecoded: 0,
      });
      continue;
    }
    // 2) Scan lines + vote.
    const payloads: string[] = [];
    const failures = new Map<string, number>();
    for (const sv of SCAN_VS) {
      const d = decodeLine(frame, pts, sv);
      if (d.payload !== undefined) payloads.push(d.payload);
      else if (d.failure) failures.set(d.failure, (failures.get(d.failure) ?? 0) + 1);
    }
    if (payloads.length === 0) {
      const top = [...failures.entries()].sort((a, b) => b[1] - a[1])[0]?.[0] ?? 'NO_START';
      out.push({
        ...base,
        decoded: false,
        confidence: 0,
        reasons: [`PIXEL:${top}`],
        scanLinesDecoded: 0,
      });
      continue;
    }
    // 3) Majority vote.
    const counts = new Map<string, number>();
    for (const p of payloads) counts.set(p, (counts.get(p) ?? 0) + 1);
    const [winner, best] = [...counts.entries()].sort((a, b) => b[1] - a[1])[0];
    const conf = best / SCAN_VS.length;
    const decoded = conf >= CONSENSUS;
    out.push({
      ...base,
      decoded,
      decodedPayload: decoded ? winner : undefined,
      confidence: decoded ? conf : 0,
      reasons: decoded ? [] : ['PIXEL:NO_CONSENSUS'],
      scanLinesDecoded: best,
    });
  }
  return out;
}
